version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run:
          command: echo build

  deploy:
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run:
          command: echo deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  deploy:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^(master|develop)$/
