version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run:
          command: echo build

  deploy:
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run:
          command: echo deploy

workflows:
  version: 2
  build:
    filters:
      branches:
        ignore: /^(master|develop)$/
    jobs:
      - build:
  build-deploy:
    filters:
      branches:
        ignore: /.*/
        only: /^(master|develop)$/
    jobs:
      - build
      - deploy:
          requires:
            - build
